### ISSUE TITLE
How do you connect to an NREPL running in Docker?

### ISSUE THREAD

**Issue by chooie** [adzerk-oss/boot-cljs-repl#53]
My task:
```
(boot/deftask start-development
  []
  (comp
    (wordroot-util/data-readers)
    (wordroot-ide-integration/cider)
    (boot-task/watch)
    (boot-reload/reload
      :port 33215
      :ws-port 33215
      :asset-path "public"
      :on-jsload 'wordroot.core/go)
    (boot-cljs-repl/cljs-repl
      :nrepl-opts {:ws-host "0.0.0.0"
                   :port    9009}
      :ws-host "0.0.0.0"
      :port 9009
      :ids #{"public/js/main"})
    (build-dev)
    (start-app)))
```

Excerpt from docker-compose.yml:
```
.
.
.
services:
  web:
    container_name: wordroot_web
    build: .
    environment:
     - IS_RUNNING_IN_CONTAINER=yes
    volumes:
     - .:/wordroot
    ports:
     - "80:80"            # Production
     - "8000:8000"   # Dev
     - "9009:9009"   # Clojure REPL
     - "33215:33215" # Resource reloading
    links:
     - db
.
.
.
```

Connecting on the host machine:
`boot repl -c -p 9009 -H "0.0.0.0"`

Error message:
```
SocketException The transport's socket appears to have lost its connection to the nREPL server
	clojure.tools.nrepl.transport/bencode/fn--1560/fn--1561 (transport.clj:95)
	clojure.tools.nrepl.transport/bencode/fn--1560 (transport.clj:95)
	clojure.tools.nrepl.transport/fn-transport/fn--1532 (transport.clj:42)
	clojure.core/binding-conveyor-fn/fn--4676 (core.clj:1938)
	java.util.concurrent.FutureTask.run (FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
	java.lang.Thread.run (Thread.java:745)
Bye for now!
```

Things I've tried switching up:
- Changing the -H option for `boot repl` to the Docker container's IP address
    - Same issue

Apologies if this is not the right place for this. Let me know and I'll take it down.

Thanks for any help.
